### ISSUE TITLE
Make it possible to download weekly snapshots automatically

### ISSUE THREAD

**Issue by kirillbobyrev** [clangd/vscode-clangd#152] opened 2021-02-18 12:14 UTC
We already have a very neat mechanism allowing users to download latest version of Clangd if it's missing from `$PATH`. Some users are eager to try the latest features we offer and hence are affected by the bugs in the weekly snapshots. We fix these bugs but we still place the burden of updating and remembering about these issues on the users. It would be nice to introduce an option (e.g. `clangd.release_track: "nighly"/"stable"`) so that power users can get an access to our nightly snapshots without pain.

**Comment by njames93** [comment] 2021-02-18 16:26
Duplicate of #49

**Comment by kirillbobyrev** [comment] 2021-02-18 16:30
Uh, good point, thanks!

**Closed** 2021-02-18 16:30 UTC
Labels: enhancement
