### ISSUE TITLE
'Include' snippets lose IntelliSense

### ISSUE THREAD

**Issue by itsVyasi** [clangd/vscode-clangd#173] opened 2021-03-26 15:30 UTC
Selecting the 'include' snippets pastes in, but fails to immediately suggest headers. For example, type "#incl" and select the snippet, then type "str". Expected behavior is that headers matching "str" are suggested, such as "string.h", but they are not.

**System information**
Clangd version (from the log, or `clangd --version`): 11.1.0
clangd extension version: 0.1.11
Operating system: macOS 10.15.7

**Comment by HighCommander4** [comment] 2021-03-26 18:16
After typing "#incl", you have to press the trigger key (e.g. Ctrl+space) to get the snippet suggestion, right?

And then, after you type "str", if you press the trigger key again, you get "string.h" suggested?

As far as I can tell, that seems to be working as intended.

**Comment by itsVyasi** [comment] 2021-03-27 03:16
Typing "#" does not trigger the snippet, but "#i" does. 



> After typing "#incl", you have to press the trigger key (e.g. Ctrl+space) to get the snippet suggestion, right?
Typing "#" does not trigger the snippet, but typing "#i" actually does.

> And then, after you type "str", if you press the trigger key again, you get "string.h" suggested?
Yes, that's correct, but I have yet to run into a case where I don't immediately use Ctrl-space to trigger IntelliSense, so I would hope that the language server does this by default.

> As far as I can tell, that seems to be working as intended.
Hmm, maybe it's more of a feature request then.

**Comment by sam-mccall** [comment] 2021-03-31 14:07
> Hmm, maybe it's more of a feature request then.

This isn't something the language server can control, it's an LSP/editor issue. So it's a feature request for language-server-protocol and/or VSCode, I guess.
(LSP describes how the client can trigger completion, and lets the server say "trigger completion after typing X characters", but there's no standard facility for triggering code completion again after inserting a completion)

**Comment by njames93** [comment] 2021-03-31 14:55
Just my $0.02, but maybe there could be a proposal to extend completion results to include a new field for completions where once completed another completion should be triggered. Possibly named along the lines of `partialCompletion` or `continuousCompletion`.
I could imagine this being useful for modules, namespaces and in this case file paths.

**Comment by itsVyasi** [comment] 2021-03-31 16:50
> Just my $0.02, but maybe there could be a proposal to extend completion results to include a new field for completions where once completed another completion should be triggered. Possibly named along the lines of `partialCompletion` or `continuousCompletion`.

 I don't even know where to open a proposal for the LSP, but I like the idea.


> (LSP describes how the client can trigger completion, and lets the server say "trigger completion after typing X characters", but there's no standard facility for triggering code completion again after inserting a completion)

I should clarify. I'm not expecting to trigger code completion immediately after inserting the snippet, I'm expecting to trigger code completion after typing the first character of a filename. As I understood it you were referring to the former?

I opened this issue because this behavior DOES work with the `for` snippet inside a function body, ie. type "for" select the snippet, then type "i" and suggestions including `int` are shown. These suggestions work with all the tabstops after typing a single character.

I also just realized `editor.suggest.snippetsPreventQuickSuggestions` affects this behavior, and I have it set to false so that snippets don't prevent IntelliSense. The suggestions after typing in the `for` snippet that I just described only appear if this is set to false.

**Comment by sam-mccall** [comment] 2021-03-31 21:09
Ooh,

**Comment by sam-mccall** [comment] 2021-03-31 21:24
Ooh, sorry, I misunderstood indeed!

The first completion seems to be a red herring. Repro steps:
 - type `#include <`
 - move the cursor away and place it after `<` again (or just dismiss the completion popup)
 - type `s`
 - no completions (unlike in other contexts)

This is VSCode specific behavior, it's detecting the context and declining to trigger completion inside strings.

Looks like this can be fixed with

```
"editor.quickSuggestions": {
        "strings": true
    },
```
https://code.visualstudio.com/docs/editor/intellisense#_settings

**Closed by sam-mccall** 2021-03-31 21:24 UTC
Labels: bug

**Comment by itsVyasi** [comment] 2021-04-01 02:37
Ah, perfect! That gets it working the way I wanted. I think a true solution would be to add the trigger you both mentioned to the LSP, I'll look into opening a feature request there.
