### ISSUE TITLE
Can "Call hierarchy" show like clion?(With the class name, not just function name)

### ISSUE THREAD

**Issue by VonSdite** [clangd/vscode-clangd#418] opened 2022-11-28 06:46 UTC
Clion Call hierarchy like this:

![image](https://user-images.githubusercontent.com/25704948/204209839-63d4dbdc-95d8-41d9-8212-5dd5ccd8d2d3.png)

**Comment by HighCommander4** [comment] 2022-11-28 06:57
Dupe of https://github.com/clangd/clangd/issues/1185.

**Closed by HighCommander4** 2022-11-28 06:57 UTC
Labels: enhancement
