### ISSUE TITLE
Debian clangd-13 version can't get parsed

### ISSUE THREAD

**Issue by mgerhardy** [clangd/vscode-clangd#279] opened 2022-01-10 09:25 UTC
The version that the debian clangd prints can't get parsed

**Logs**
![Bildschirmfoto von 2022-01-10 10-21-50](https://user-images.githubusercontent.com/577713/148743324-bfd0a173-c3c3-4b80-9058-8753af9eb0bf.png)

**System information**
```bash
clangd --version
Debian clangd version 13.0.0-9+b2
Features: linux
Platform: x86_64-pc-linux-gnu
```

clangd extension version:
Version 0.1.13: August 24, 2021

Operating system:
```bash
lsb_release  -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bookworm/sid
Release:	testing
Codename:	bookworm
```

**Comment by HighCommander4** [comment] 2022-01-25 06:11
Duplicate of https://github.com/clangd/node-clangd/issues/6.

**Closed by HighCommander4** 2022-01-25 06:11 UTC
Labels: bug
