### ISSUE TITLE
Code suggestions are not accord with .clang-format config

### ISSUE THREAD

**Issue by UniverGao** [clangd/vscode-clangd#754] opened 2024-12-11 08:21 UTC
I pushed the `.clang-format` file to the root location of project, and set up correctly, then I tried the `format document` command, the config file worked well. 
But when I typed the keywords(such as `if` `else`), then the config file seemed not work for code block

I wonder if this issue is existed, and this function is quiet important for me

**1 Try the `Format Document`:**
![image](https://github.com/user-attachments/assets/9b90ac94-8c6b-40ac-a93b-44eb26d7d566)

![image](https://github.com/user-attachments/assets/9999642d-9ce3-4033-bc5c-db969b93a1cb)

**2. Type the keywords:**

![屏幕截图 2024-12-11 161855](https://github.com/user-attachments/assets/246a6271-de86-4e80-85e2-8d9ca42b7e73)

The snippet of keyword is not same as the config file

![image](https://github.com/user-attachments/assets/74bcb4e3-cbb3-4687-860e-96aac7978e0e)

**Comment by HighCommander4** [comment] 2024-12-12 06:55
I believe this is a duplicate of https://github.com/clangd/clangd/issues/1235.

**Closed** 2024-12-16 04:03 UTC
Labels: bug
