### ISSUE TITLE
Automatically selecting auto completion suggestion despite not pressing enter or tab key

### ISSUE THREAD

**Issue by lakshits11** [clangd/vscode-clangd#357] opened 2022-07-11 19:18 UTC
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

After todays update to version 0.1.18, it automatically selects the auto completion suggestion.

![image](https://user-images.githubusercontent.com/54276661/178340544-ff4dc98f-cdf5-47c4-bc8e-9d9c4484647a.png)

For example if i write `while` and then when i open a curved bracket without clicking or selecting the while snippet suggestion, it automatically selects that snippet without my wish and finally it looks like this:
![image](https://user-images.githubusercontent.com/54276661/178340466-f03be8d2-31ee-4feb-b332-2fdfb32061ea.png)

There are two brackets inside while loop, one is mine and other is snippet's.

Same problem is also occuring in `if` and also many other conditions/loops etc. 

> When I reverted back to older version, the problem disappeared.

**Logs**
Please attach the clangd log from the "Output" window if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
```
I[00:44:13.619] --> textDocument/clangd.fileStatus
I[00:44:13.619] --> textDocument/clangd.fileStatus
I[00:44:13.621] --> workspace/semanticTokens/refresh(37)
I[00:44:13.621] --> textDocument/clangd.fileStatus
I[00:44:13.621] --> textDocument/clangd.fileStatus
I[00:44:13.621] --> textDocument/clangd.fileStatus
I[00:44:13.621] <-- reply(37)
```

**System information**
Clangd version (from the log, or `clangd --version`): 
![image](https://user-images.githubusercontent.com/54276661/178340956-9d37e5a0-d244-43a4-aa3c-88e0464827a4.png)

clangd extension version: `0.1.18`
Operating system: Manjaro XFCE

**Comment by jasonwzz** [comment] 2022-07-12 14:15
I noticed something like this as well but I thought this is expected from `editor.acceptSuggestionOnCommitCharacter` being fixed with the newer version (https://github.com/clangd/vscode-clangd/issues/347). I turned acceptSuggestionOnCommitCharacter off to get back to what it was. Is my understanding incorrect that this is actually not expected or is this a different issue?

**Closed** 2022-07-12 19:53 UTC
Labels: bug

**Comment by HighCommander4** [comment] 2022-07-15 07:36
Doesn't the approach taken here take control away from users, in that previously if they didn't like this behaviour they could turn off `editor.acceptSuggestionsOnCommitCharacter`, but if they do like (see #347) now there's no way to turn it back on?

**Comment by sam-mccall** [comment] 2022-07-15 14:28
Strictly: no, because this never worked! (except for ~1 day, with 0.1.19)

Relative to if we set the commit characters: yes, absolutely, and i think this is a problem.

However if the default behavior is extremely broken, that's a big problem. Exacerbated by:
- many users won't explore the settings
- it's not obvious what to change to fix this, symptoms are intuitive ("completion feels wrong") and it takes some investigation even to work out what you want

I might be wrong about this behavior being very broken - it seems jrieken likes it, there must be at least one other! @HighCommander4 did you manage to reproduce the behavior in vscode? I find it incredibly jarring, more than it looks like on paper.

**Comment by HighCommander4** [comment] 2022-07-16 07:39
> @HighCommander4 did you manage to reproduce the behavior in vscode?

Yeah, you were right that the reason I wasn't seeing the auto-activation was due to `editor.quickSuggestions.other: off`, and the commit behaviour due to being on an older vscode-clangd than 0.1.18.

Having now installed 0.1.18 to see what it's like, I agree that interaction between the `(` commit character and snippets is bad, and means that `(` probably shouldn't be a commit character until vscode fixes that somehow (or at least, not a commit character when snippets are enabled?)

Some of the other commit characters seem fine, though, and some like `;` and `.` in particular seem useful -- perhaps we could consider bringing back a more restricted set?
