### ISSUE TITLE
Can we have options to let autocompletion only complete the function name (without parenthesis and parameter)

### ISSUE THREAD

**Issue by zyd2001** [clangd/vscode-clangd#627] opened 2024-04-28 21:15 UTC
Most code completion plugins have the option to disable autocompletion adding parenthesis and I'm quite used to that behavior. However, there is no such option with vscode-clangd. 
I'm not sure whether it is a clangd server issue, but with my experience with LSP interface in neovim, disabling the LSP capabilities' `textDocument.completion.completionItem.snippetSupport` can achieve this.

**Comment by HighCommander4** [comment] 2024-04-28 23:19
vscode-clangd doesn't control the value of the `snippetSupport` capability, that's set by the vscode-languageclient plugin (which is shared by all languages), and it looks like that [harcodes it](https://github.com/microsoft/vscode-languageserver-node/blob/31fe8fea47fe4ae4e0494413826d33ee898a1ee0/client/src/common/completion.ts#L77) to `true`.

However, clangd does have a server-side setting to disable argument placeholders, by passing `--function-arg-placeholders=0` as a command-line argument to clangd. (In vscode, this can be specified with the `"clangd.arguments"` setting).

Parentheses are still inserted with `--function-arg-placeholders=0`. There is an issue on file about adding a more flexible setting which can also control insertion of parentheses: https://github.com/llvm/llvm-project/issues/63565.

**Comment by HighCommander4** [comment] 2024-04-28 23:19
Duplicate of https://github.com/llvm/llvm-project/issues/63565

**Closed by HighCommander4** 2024-04-28 23:19 UTC
Labels: enhancement
