### ISSUE TITLE
quick fix can't show add definition to .cpp files?

### ISSUE THREAD

**Issue by aiyolo** [clangd/vscode-clangd#620] opened 2024-04-13 08:09 UTC
when I use other IDE, after I write function decraretion in .h file, I can use alt+enter to add an empty definition to .cpp files. It seems that clangd doesn't supprt this feature. 

I just wonder that people using clangd how to deal with this situation?

**Comment by HighCommander4** [comment] 2024-04-13 15:51
If you type an empty definition (`{}` instead of `;` at the end of the function), then a "Move function body out of line" code action is available.

**Comment by HighCommander4** [comment] 2024-04-13 15:55
For a code action that works on declarations, we have https://github.com/clangd/clangd/issues/445 on file.

**Comment by HighCommander4** [comment] 2024-04-13 15:55
Duplicate of https://github.com/clangd/clangd/issues/445

**Closed by HighCommander4** 2024-04-13 15:55 UTC
Labels: bug
