### ISSUE TITLE
Hope add configuration of the location of index files 

### ISSUE THREAD

**Issue by rmGFW** [clangd/vscode-clangd#430] opened 2022-12-31 16:11 UTC
the default path of index file is in the project root , and it will lead to lots of git changes (Although I can add it to gitignore ,but i still want i can configuration the index path )

**Comment by HighCommander4** [comment] 2022-12-31 21:42
Duplicate of https://github.com/clangd/clangd/issues/184

**Closed by HighCommander4** 2022-12-31 21:42 UTC
Labels: enhancement
