### ISSUE TITLE
the quick-fix has not use .clang-format info

### ISSUE THREAD

**Issue by walkthetalk** [clangd/vscode-clangd#462] opened 2023-03-01 03:40 UTC
when using quick-fix function, the .clang-format file is not considered, which result in ugly format code.

e.g. 
.clang-format has following content:
```
BraceWrapping:
  BeforeElse:      true
```
when quick-fix of:
```
   if (xxx)
      yyy;
```
result in:
```
   if (xxx) {
   yyy;
}
```

**Comment by HighCommander4** [comment] 2023-03-01 05:46
Duplicate of https://github.com/clangd/clangd/issues/969

**Closed by HighCommander4** 2023-03-01 05:46 UTC
Labels: bug
