### ISSUE TITLE
Issue with #include autocompletion removing closing quote

### ISSUE THREAD

**Issue by ernesto-glz** [clangd/vscode-clangd#635] opened 2024-05-27 09:12 UTC
When accepting a suggestion in an `#include` statement, if the suggestion contains a trailing `/` (indicating a folder), it removes the closing quote (`"`) from the `#include` statement. However, when accepting suggestions that point to a file, such as `bar.h`, it works perfectly.

![image](https://github.com/clangd/vscode-clangd/assets/80600689/7069d773-1a5a-44ec-8fdd-20020d7275e4)
![image](https://github.com/clangd/vscode-clangd/assets/80600689/12121d35-2bcb-4d2a-99f7-fd8c6d8bc959)

**System information**
clangd version 17.0.1
clangd extension version: 0.1.28
os: windows 11

**Comment by HighCommander4** [comment] 2024-05-28 05:42
I believe this is intentional: you cannot include a directory, so at the point where a completion item referring to a directory has been accepted, the `#include` statement is still incomplete. You can then invoke completion again to select a file, at which point the closing quote will be inserted.

**Comment by ernesto-glz** [comment] 2024-05-28 12:49
> I believe this is intentional: you cannot include a directory, so at the point where a completion item referring to a directory has been accepted, the `#include` statement is still incomplete. You can then invoke completion again to select a file, at which point the closing quote will be inserted.

This is not the case for the vscode cpp tools extension or the visual studio IDE, you can accept folder suggestions and after that it will suggest the folders and files inside of it, this results in less tedious work to write large include paths.

Also, what's the point of having folders suggestions if you cannot accept it to write less because if you do then the extension will remove the closing quote and would not  suggest anything else until you explicitly press ctrl + space.

I hope this explanation will make you understand my point of view because I used the IDE for two years and this is life saver in large projects with tons of folders. Thanks.

**Comment by HighCommander4** [comment] 2024-05-29 04:31
So, if I understand correctly, the issue is not really about the closing quote, but rather that after completing the folder, completion is not automatically activated for the files in the folder?

**Comment by ernesto-glz** [comment] 2024-05-29 08:35
> So, if I understand correctly, the issue is not really about the closing quote, but rather that after completing the folder, completion is not automatically activated for the files in the folder?

Nope, the issue is that you cannot chain suggestions because if the first folder suggestion  removes the closing quote, the extension will not suggest anything else because again the `#include` statement is objectively broken after that.

A good example will be this:
- I have this path `/lib/foo/bar/baz.h`
- While writing the path i cannot accept the suggestions for `foo` or `bar` because they are folders and because of that the autocomplete is useless until i reach the point where the header file is located an i can accept the suggestion.

In VS2022 if you accept `/lib` suggestion it will suggest `foo` after that anf then `bar` and then `baz.h`.

**Comment by ernesto-glz** [comment] 2024-05-29 08:41
> > So, if I understand correctly, the issue is not really about the closing quote, but rather that after completing the folder, completion is not automatically activated for the files in the folder?
> 
> Nope, the issue is that you cannot chain suggestions because if the first folder suggestion  removes the closing quote, the extension will not suggest anything else because again the `#include` statement is objectively broken after that.
> 
> A good example will be this:
> - I have this path `/lib/foo/bar/baz.h`
> - While writing the path i cannot accept the suggestions for `lib`, `foo` or `bar` because they are folders and because of that the autocomplete is useless until i reach the point where the header file is located an i can accept the suggestion.
> 
> In VS2022 if you accept `/lib` suggestion it will suggest `foo` after that and then `bar` and then `baz.h`. And here after you accept `/lib` the extension will break the #include "" statement and because of that also stop the autocomplete.

**Comment by HighCommander4** [comment] 2024-05-30 07:12
> the issue is that you cannot chain suggestions because if the first folder suggestion removes the closing quote, the extension will not suggest anything else because again the `#include` statement is objectively broken after that

Just to clarify: when you say "the extension will not suggest anything else", you mean it will not **automatically** suggest the next segment of the path, right? (i.e. it does work if you press the keyboard shortcut to manually trigger suggestions, e.g. <kbd>Ctrl</kbd>+<kbd>Enter</kbd>?)

**Comment by ernesto-glz** [comment] 2024-05-30 09:35
> > the issue is that you cannot chain suggestions because if the first folder suggestion removes the closing quote, the extension will not suggest anything else because again the `#include` statement is objectively broken after that
> 
> Just to clarify: when you say "the extension will not suggest anything else", you mean it will not **automatically** suggest the next segment of the path, right? (i.e. it does work if you press the keyboard shortcut to manually trigger suggestions, e.g. Ctrl+Enter?)

Yes `Ctrl` + `Space`  is my  shortcut but imagine doing that for paths that have 5 to 6 nested folders every time just because the extension removes the closing quote.

Here is how VS works:

https://github.com/clangd/vscode-clangd/assets/80600689/1f7eb8a9-0473-4cfe-bc57-136967877e2a

**Comment by HighCommander4** [comment] 2024-05-31 01:29
Thank you for the clarification.

So what I was trying to say earlier is that the behaviour you care about is the automatic activation of completion for the next segment.

The absence of the closing quote might be unrelated to the activation behaviour.

**Comment by HighCommander4** [comment] 2024-05-31 02:14
> The absence of the closing quote might be unrelated to the activation behaviour.

Indeed, as an experiment I prototyped a change that preserves the closing quote. No difference in activation behaviour (you still have to press <kbd>Ctrl</kbd>+<kbd>Space</kbd>).

The cause of the activation behaviour issue is something else.

**Comment by HighCommander4** [comment] 2024-05-31 02:19
> The cause of the activation behaviour issue is something else.

It looks like we have an issue on file about this: https://github.com/clangd/clangd/issues/395

I'll close this one as a duplicate.

**Comment by HighCommander4** [comment] 2024-05-31 02:19
Duplicate of https://github.com/clangd/clangd/issues/395

**Closed** 2024-05-31 02:19 UTC
Labels: bug
