### ISSUE TITLE
not support with remote docker in mac m1

### ISSUE THREAD

**Issue by tiny1990** [clangd/vscode-clangd#434] opened 2023-01-04 15:13 UTC
**Logs**

remote-docker on mac m1 and install clangd, but update clangd or download clang use vscode-clangd failed

vscode-clangd need check aarch64/arm64 ?

<img width="456" alt="Screenshot 2023-01-04 at 23 08 33" src="https://user-images.githubusercontent.com/3408822/210586112-ff3eadc9-5440-4789-81e3-4ab8604baf2d.png">

**System information**
Debian clangd version 15.0.6
Features: linux+grpc
Platform: aarch64-unknown-linux-gnu

**Comment by HighCommander4** [comment] 2023-01-06 09:10
We don't currently ship standalone ARM builds of clangd; #514 is on file for it.

The LLVM project does provide ARM builds that include clangd, you can get one from e.g. https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.6.

**Comment by kadircet** [comment] 2023-01-17 14:07
closing as duplicate of https://github.com/clangd/clangd/issues/514

**Closed by kadircet** 2023-01-17 14:07 UTC
Labels: bug
