### ISSUE TITLE
Doxygen comments not shown properly in tooltips

### ISSUE THREAD

**Issue by davidavetyan** [clangd/vscode-clangd#585] opened 2024-02-20 09:52 UTC
clangd displays doxygen comments as plain text in the tooltip, unlike the default C/C++ extension of VS code.
For example for the code below:
```
/**
    \brief Example function for adding

    \param num1 First number to add
    \param num2 Second number to add

    \return Sum of \p num1 and \p num2
*/
int add(int num1, int num2)
{
    return num1 + num2;
}
```
C/C++ extension's intellisense shows the tooltip like so:
![image](https://github.com/clangd/vscode-clangd/assets/30115424/379ffe64-8ab6-4c66-bbf5-f57ddcb2cdac)

While clangd shows it like this:
![image](https://github.com/clangd/vscode-clangd/assets/30115424/a7c202a4-38c2-4b10-b92a-313145f9c297)

**Comment by HighCommander4** [comment] 2024-02-21 05:03
Duplicate of https://github.com/clangd/clangd/issues/529

**Closed by HighCommander4** 2024-02-21 05:03 UTC
Labels: bug
