### ISSUE TITLE
Build AST for all files instead of currently opend file

### ISSUE THREAD

**Issue by imageslr** [clangd/vscode-clangd#407] opened 2022-11-05 15:51 UTC
Hi, I am using clangd extension to navigate through my c++ files. I have noticed that the extension will only build AST for the file that are opened. Everytime I open a new file, there will be a message in the output panel:

```
I[23:43:31.628] ASTWorker building file xxxcpp version 1 with command 
```

It would be better if clangd can build AST for all files in the background, so when I open a new file, I don't have to wait before the ASTWorker building is finished.

Thanks.

**Comment by HighCommander4** [comment] 2022-11-05 18:46
I believe this is basically a duplicate of https://github.com/clangd/clangd/issues/589. Some additional relevant discussion can be found in https://github.com/clangd/clangd/issues/1165.

**Closed by HighCommander4** 2022-11-05 18:46 UTC
Labels: enhancement

**Comment by imageslr** [comment] 2022-11-06 03:32
Thanks a lot！
