### ISSUE TITLE
Breaks on universal builds

### ISSUE THREAD

**Issue by gotschmarcel-ni** [clangd/vscode-clangd#270] opened 2021-12-13 16:51 UTC
Completely breaks when used in a CMake project that generates a compilation database for universal builds, because the generated compile commands database contains two commands per file:

```json
[
  {
    "directory": "/Users/Some/Developer/build",
    "command": "/usr/bin/clang++ [opts] Some.cpp",
    "file": "/Users/Some/Developer/source/Some.cpp"
  },
  {
    "directory": "/Users/Some/Developer/build",
    "command": "/usr/bin/clang++ [opts] Some.cpp",
    "file": "/Users/Some/Developer/source/Some.cpp"
  }
]
```

Flag in CMake to trigger this:
```
set(CMAKE_OSX_ARCHITECTURES arm64;x86_64)
```

**Logs**

I[17:44:42.098] <-- textDocument/codeAction(22)
I[17:44:42.098] --> reply:textDocument/codeAction(22) 0 ms, error: invalid AST

**Error Message in Problems Section**

```
Unable to handle compilation, expected exactly one compiler job in ' "/usr/bin/clang++" <opts...> "Some.cpp";  "/usr/bin/clang++" 
<opts...> "Some.cpp"; '
```

**System information**

Clangd version Apple clangd 13.0.0
clangd extension version: v0.1.13
Operating system: macOS Monterey 12.0.1

**Comment by HighCommander4** [comment] 2021-12-13 20:35
I don't think the fact that file entries are duplicated in the CDB, in and of itself, is a problem. At least, when I duplicate some entries locally, that works fine.

To diagnose the issue further, please post the exact compile command (or preferably, a complete clangd log from the Output view).

**Comment by sam-mccall** [comment] 2021-12-13 21:24
Agree with @HighCommander4. It's not very helpful to redact all the details from the logs, I understand you think you know what the issue is but in this case you're mistaken.

I happen to recognize this one though, it's that a single command with multiple arch flags (to create a mach-o fat object file) encodes multiple internal compilation steps (cc1 invocations). Clangd wasn't sure which one to pick.
This was fixed in https://github.com/llvm/llvm-project/commit/2ff7ca98a99bbfc4f44b8ba1e2e4e594f8ee253e which is unfortunately not released yet, but will be in clangd 14. You can pick up a recent snapshot from https://github.com/clangd/clangd/releases

> Clangd version Apple clangd 13.0.0

Note that these "apple clangd" versions don't correspond to LLVM or clangd version numbers, but are XCode versions. Apple clang 13 is slightly older than LLVM 12.

**Closed by sam-mccall** 2021-12-13 21:24 UTC
Labels: bug

**Comment by gotschmarcel-ni** [comment] 2021-12-15 10:43
I apologise for redacting all of the options, but this command was very long and contained confidential information. Thanks for your help.

**Comment by sam-mccall** [comment] 2021-12-15 17:10
No worries. There's a workaround in https://github.com/clangd/clangd/issues/827#issuecomment-893761748, I'll add it to the FAQ
