### ISSUE TITLE
costom path support with '.clangd .clang-format'

### ISSUE THREAD

**Issue by USTHzhanglu** [clangd/vscode-clangd#679] opened 2024-09-03 10:49 UTC
with `Microsoft C/C++ extension`,i use `C_Cpp.clang_format_style": "file:${workspaceFolder}/sdk/.clang-format`
to specify my config file.
with clangd, It looks like it must exist in the project root directory. 
could have any arguments let clang-format use file:custom_path?
thanks for any answer

**Comment by HighCommander4** [comment] 2024-09-03 22:14
Duplicate of https://github.com/clangd/clangd/issues/805

**Closed by HighCommander4** 2024-09-03 22:14 UTC
Labels: enhancement
