### ISSUE TITLE
No longer possible to use cmd as clangd executable

### ISSUE THREAD

**Issue by JVApen** [clangd/vscode-clangd#683] opened 2024-09-12 09:44 UTC
The VS Code upgrade to 1.92 contains a new node version (20)
This version seems to have as a side effect that scripts can no longer be used as 'executable' on windows
(see similar issue for cmake: https://github.com/microsoft/vscode-cmake-tools/issues/4037#issuecomment-2331286590)

When using VS Code with 1.91, I can use a clangd.cmd that figures out the clangd version to use (the same as we use to compile). However from VS Code 1.92 this is no longer possible. 

I'm no expert in typescript, though I believe this behavior can be re-enabled in ClangdContext::active by passing "shell: true" as part of the options of vscodelc.Executable.

**Logs**

````
[Error - 11:31:01 AM] Clang Language Server client: couldn't create connection to server.
Error: spawn EINVAL
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:800:9)
	at c:\Users\JVA\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.29\out\bundle.js:39:56906
	at async oc.createConnection (c:\Users\JVA\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.29\out\bundle.js:39:12067)
	at async oc.start (c:\Users\JVA\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.29\out\bundle.js:39:2940)
````

**System information**

Operating system: Windows

**Comment by HighCommander4** [comment] 2024-11-13 03:58
Released in 0.1.30.

**Comment by HighCommander4** [comment] 2024-11-13 22:11
Sorry, had to back out the fix for this, together with #715, for causing #722. Reopening.

**Comment by JVApen** [comment] 2024-11-14 05:20
Thanks @HighCommander4, I will be able to look at this on Friday. Thanks for reverting and as such reducing the pressure

**Comment by HighCommander4** [comment] 2024-11-22 07:23
Reverted again in #736 for causing #734.

Discussion in #734 suggests that the issue is related to the default value of `"clangd.useScriptAsExecutable"` not being handled correctly in some environments, as e.g. [this comment](https://github.com/clangd/vscode-clangd/issues/734#issuecomment-2493009718) reports the issue being resolved if the user puts an explicit `"clangd.useScriptAsExecutable": false` into their settings.

Regardless of the specific fix, I'd also like to make a process change before re-landing a fix here again: I'd like to add a way to create an "unstable" / "nightly" release that shows up in https://github.com/clangd/vscode-clangd/releases/ and allows users to download and test a ` .vsix` package, without pushing the new version to the VSCode Marketplace or OpenVSX yet. Then, we can ask users (e.g. the ones who reported experiencing #722 or #734) to test that version and verify that it works for them, before publishing the version to the marketplaces. I'll look at setting up a CI action for that in the coming days.

**Comment by HighCommander4** [comment] 2024-12-06 08:03
> I'd also like to make a process change before re-landing a fix here again: I'd like to add a way to create an "unstable" / "nightly" release that shows up in https://github.com/clangd/vscode-clangd/releases/ and allows users to download and test a ` .vsix` package, without pushing the new version to the VSCode Marketplace or OpenVSX yet. Then, we can ask users (e.g. the ones who reported experiencing #722 or #734) to test that version and verify that it works for them, before publishing the version to the marketplaces. I'll look at setting up a CI action for that in the coming days.

I put up a PR adding such a CI action at https://github.com/clangd/vscode-clangd/pull/748.

**Closed** 2024-12-22 22:50 UTC
Labels: bug
