### ISSUE TITLE
Autocompletion through liveshare

### ISSUE THREAD

**Issue by qdewaghe** [clangd/vscode-clangd#134] opened 2021-01-18 11:35 UTC
Auto-completion doesn't work through liveshare, other features seem to work correctly. There is some weirdness around syntax highlighting as well but I didn't look into it.

**Logs**

Logs when asking for autocompletion locally:
```
V[12:25:43.737] <<< {"id":117,"jsonrpc":"2.0","method":"textDocument/completion","params":{"context":{"triggerKind":1},"position":{"character":4,"line":125},"textDocument":{"uri":"file:///[redacted]"}}}
I[12:25:43.737] <-- textDocument/completion(117)
I[12:25:43.769] Code complete: sema context DotMemberAccess, query scopes [] (AnyScope=true), expected type <none>
I[12:25:43.770] Code complete: 9 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 9 returned.
I[12:25:43.770] --> reply:textDocument/completion(117) 33 ms
```

Logs when asking for autocompletion through liveshare
```
V[12:18:58.742] <<< {"id":80,"jsonrpc":"2.0","method":"textDocument/completion","params":{"context":{"triggerCharacter":null,"triggerKind":1},"position":{"character":4,"line":125},"textDocument":{"uri":"file:///[redacted]"}}}
I[12:18:58.742] <-- textDocument/completion(80)
E[12:18:58.742] Failed to decode textDocument/completion request.
I[12:18:58.742] --> reply:textDocument/completion(80) 0 ms, error: -32600: failed to decode request
V[12:18:58.742] >>> {"error":{"code":-32600,"message":"failed to decode request"},"id":80,"jsonrpc":"2.0"}
[Error - 12:18:58 PM] Request textDocument/completion failed.
 Message: failed to decode request
 Code: -32600 
```
**System information**
Clangd version : 11.0.0
clangd extension version: 0.1.9
Operating system: Ubuntu

**Comment by kadircet** [comment] 2021-01-18 11:53
I am not sure what `liveshare` is, but the provided completion request is malformed per LSP spec. As described in https://microsoft.github.io/language-server-protocol/specification#textDocument_completion, `triggerCharacter` is an optional `string`. So it either shouldn't be present at all, or should be a `string`. Whereas `liveshare` is providing a `null` which is not a `string` value per JSON. Hence clangd is failing the request with a parse error.

I am closing the issue as it seems to be related to extra layer in between, please feel free to re-open if my diagnosis doesn't seem correct.

**Closed by kadircet** 2021-01-18 11:53 UTC
Labels: bug

**Comment by qdewaghe** [comment] 2021-01-18 13:13
> I am closing the issue as it seems to be related to extra layer in between, please feel free to re-open if my diagnosis doesn't seem correct.

I assumed the issue came from this extension given the fact that `ccls` and `intellisense` work fine through `liveshare`. But it may be that they're just being a bit more permissive in regards to LSP compliance at the server level. No idea how these things work though.

**Comment by njames93** [comment] 2021-01-18 20:18
Raise an issue at liveshare about how they aren't correctly following the spec

**Comment by sam-mccall** [comment] 2021-01-18 20:34
This is all true. Raising the issue is a good idea - it's a real interop problem, and practically speaking liveshare can almost certainly release+distribute an update faster than we can.

That said, mapping this as both optional and nullable is a minor and simple change, maybe we should do it anyway. Postel's law and all that.
