### ISSUE TITLE
Add quick suggestion / function template for main().

### ISSUE THREAD

**Issue by nilshiroqaq** [clangd/vscode-clangd#479] opened 2023-05-05 16:13 UTC
Note: we mostly implement features in the clangd language server, and rely on Microsoft's LSP client framework to expose these in VSCode. Features requiring a lot of VSCode-specific work are unlikely to be implemented.

like vscode-cpptools extension  dose, if you type "main" word which usually that you want to a main() function, and cpptools do a suggest : 
int main(int argc, char const *argv[]) {
  /* code here */
  return 0;
}

and I think this will be great to be added.

**Comment by HighCommander4** [comment] 2023-05-06 02:22
Duplicate of https://github.com/clangd/clangd/issues/380

**Closed by HighCommander4** 2023-05-06 02:22 UTC
Labels: enhancement
