### ISSUE TITLE
Crash with lambda and calling convention without return type, and inlay hints

### ISSUE THREAD

**Issue by justanotheranonymoususer** [clangd/vscode-clangd#733] opened 2024-11-20 10:54 UTC
Please describe the problem.
This code causes clangd to crash:

```cpp
void test() {
    auto x = [](void*) __cdecl {};
    x(nullptr);
}
```
changing `__cdecl` to `__cdecl -> void` fixes it.

Also, important to note that the problem only reproduces if inlay hints are enabled in vscode.

I also created an [upstream bug](https://github.com/clangd/clangd/issues/2223) but it they're asking for a stack trace and there's none in the logs, and because it only crashes with inlay hints, I thought that maybe it's something with the extension.

**Logs**
```
I[12:39:51.607] clangd version 18.1.8 (https://github.com/llvm/llvm-project.git 3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff)
I[12:39:51.608] Features: windows
I[12:39:51.608] PID: 4572
I[12:39:51.608] Working directory: <dir>
I[12:39:51.608] argv[0]: <compiler_dir>/Compiler/bin/clangd.exe
I[12:39:51.611] Starting LSP over stdin/stdout
I[12:39:51.612] <-- initialize(0)
I[12:39:51.641] --> reply:initialize(0) 29 ms
I[12:39:51.642] <-- initialized
I[12:39:51.645] <-- textDocument/didOpen
I[12:39:51.647] Loaded compilation database from <dir>/compile_flags.txt
I[12:39:51.647] ASTWorker building file <dir>/test.cpp version 6 with command 
[<dir>]
"<compiler_dir>/Compiler/bin/clang-tool" "-resource-dir=<compiler_dir>/Compiler/lib/clang/18" -- <dir>/test.cpp
I[12:39:51.649] --> textDocument/clangd.fileStatus
I[12:39:51.654] <-- textDocument/documentSymbol(1)
I[12:39:51.655] <-- textDocument/documentLink(2)
I[12:39:51.655] <-- textDocument/inlayHint(3)
I[12:39:51.664] Built preamble of size 230280 for file <dir>/test.cpp version 6 in 0.01 seconds
I[12:39:51.665] --> workspace/semanticTokens/refresh(0)
I[12:39:51.666] <-- reply(0)
I[12:39:51.671] Indexing c++17 standard library in the context of <dir>/test.cpp
I[12:39:51.674] <-- textDocument/semanticTokens/full(4)
I[12:39:51.700] --> textDocument/publishDiagnostics
I[12:39:51.700] --> textDocument/inactiveRegions
I[12:39:51.700] --> reply:textDocument/documentSymbol(1) 46 ms
I[12:39:51.700] --> reply:textDocument/documentLink(2) 44 ms
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Signalled during AST worker action: InlayHints
  Filename: <dir>/test.cpp
  Directory: <dir>
  Command Line: <compiler_dir>/Compiler/bin/clang-tool -resource-dir=<compiler_dir>/Compiler/lib/clang/18 -- <dir>/test.cpp
  Version: 6
Exception Code: 0xC0000005
I[12:39:51.852] <-- textDocument/foldingRange(5)
I[12:39:51.853] --> reply:textDocument/foldingRange(5) 0 ms
[Info  - 12:39:51 PM] Connection to server got closed. Server will restart.
[Error - 12:39:52 PM] Request textDocument/inlayHint failed.
[object Object]
[Error - 12:39:52 PM] Request textDocument/semanticTokens/full failed.
[object Object]
```

**System information**
Clangd version (from the log, or `clangd --version`):
```
clangd version 18.1.8 (https://github.com/llvm/llvm-project.git 3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff)
Features: windows
Platform: i686-w64-windows-gnu; target=i686-w64-mingw32
```
clangd extension version: v0.1.29 
Operating system: win11

**Comment by HighCommander4** [comment] 2024-11-22 06:56
I posted a fix at https://github.com/clangd/clangd/issues/2223. I'll close this ticket as the issue is on the server side.

**Closed by HighCommander4** 2024-11-22 06:56 UTC
Labels: bug
