### ISSUE TITLE
Including inl files in header files with templates causes issues

### ISSUE THREAD

**Issue by smeznaric** [clangd/vscode-clangd#208] opened 2021-07-09 15:39 UTC
Example:

some_file.h

```
#pragma once

void some_func_with_defaults(int x = 1);

template <typename T>
void some_func(T x);

#include <some_file.inl>
```

some_file.inl

```
#include <some_file.h> //for intellisense, not strictly needed otherwise

template <typename T>
void some_func(T x)
{
    //Function definition
}
```

some_file.cpp:
```
#include <some_file.h>

void some_func_with_defaults(int x)
{
    //do something
}
```

The issue with the above is that the line `#include <some_file.inl>` is not happy because some_file.inl include some_file.h so it thinks default arguments are being redefined. And some_file.inl is unhappy on `#include <some_file.h>` because both files are including each other so it wants inl to not include .h. But doing that, although perfectly valid, leads to a lot of underlined code.

My suggestion would be to somehow recognise the special status of files that are used for inlining the templated functions.

**System information**
Clangd version (from the log, or `clangd --version`): 13.0.0
clangd extension version: 0.1.11
Operating system: Centos 7

**Comment by HighCommander4** [comment] 2021-07-09 21:09
I believe this is the same code pattern as in https://github.com/clangd/clangd/issues/377, and we can consider this a duplicate of that one.

**Closed by HighCommander4** 2021-07-09 21:09 UTC
Labels: bug
