### ISSUE TITLE
Subject: Clangd Not Functioning Properly in Specific Workspace

### ISSUE THREAD

**Issue by DYAAL** [clangd/vscode-clangd#641] opened 2024-06-17 12:50 UTC
Hi, today I encountered a strange issue while working. My Clangd suddenly stopped functioning normally, and the problem only occurs in the current workspace. Other workspaces don't have this issue.

The problem appeared suddenly during use, with Clangd failing to parse and navigate correctly. I have verified that compile_commands.json is in the correct path and the index is properly generated, but it still doesn't work correctly. I have attached compile_commands.json and clangd.log in hopes that you can help me.
[clangd.log](https://github.com/user-attachments/files/15871102/clangd.log)
![1718628473944](https://github.com/clangd/vscode-clangd/assets/126035353/768a58cb-1701-4dab-b618-48421df5bab2)
[compile_commands.json](https://github.com/user-attachments/files/15871117/compile_commands.json)

**Comment by HighCommander4** [comment] 2024-06-18 03:43
Is this a duplicate report of https://github.com/clangd/clangd/issues/2070?

**Comment by DYAAL** [comment] 2024-06-18 05:53
yes

**Comment by HighCommander4** [comment] 2024-06-18 22:37
Duplicate of https://github.com/clangd/clangd/issues/2070

**Closed by HighCommander4** 2024-06-18 22:37 UTC
Labels: bug
