### ISSUE TITLE
Automatic binary installation not working in remote development use case

### ISSUE THREAD

**Issue by ChristianKuehnel** [clangd/vscode-clangd#112] opened 2020-12-07 15:21 UTC
I'm running VSCode 1.51 on MacOS and want to do remote development (via SSH) on a Linux machine (Ubuntu 18.04). Neither of the machines has a `clangd` binary on the `PATH`.
 
1. I installed the clangd extension 0.1.8 from the integrated Marketplace.  
1. On the first start of the extension, it asks me if I want to install clangd and I clicked on "Install".
1. After a every restart of VSCode it asks me again, if I want to install it.
1. It never actually starts the clangd binary.

On the local machine (MacOS), the clangd path ends up in `/Users/<username>/Library/Application Support/Code/User/settings.json`. I guess this should be stored on the remote machine instead.
```json
{
    "clangd.path": "<homedir>/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/bin/clangd",
}
```

My remote machine does not have any `settings.json`.

I can also reproduce the issue when using Windows as local OS and the same Ubuntu machine as remote.

Workaround:
Hard-code the install path in the `.vscode/settings.json` in the workspace:
```json
{
  "clangd.path": "<homedir>/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/bin/clangd",
  "cmake.configureOnOpen": false
}
```

**Logs**
Please attach the clangd log from the "Output" window if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

**System information**
Clangd version (from the log, or `clangd --version`): clangd version 11.0.0 (https://github.com/llvm/llvm-project 176249bd6732a8044d457092ed932768724a6f06)
clangd extension version: 0.1.8
Operating system: MacOs 10.15.07 / Ubuntu 18.04

**Comment by kadircet** [comment] 2021-01-20 13:09
closing as this is a duplicate of #25

**Closed by kadircet** 2021-01-20 13:09 UTC
Labels: bug
